### ISSUE TITLE
VOA

### ISSUE THREAD

**Issue by ghost** [zyz0000/ACE2005_preprocessing#1]
Hi Yuzhe, have you downloaded the VOA dataset? Do you have a method of quickly downloading? It consumes too much time. Thank you very much.

**Comment by zyz0000** [comment]
Yes, I have downloaded VOA dataset. I modified the original download script into multiprocessing format.
```python
import os
import requests
import json
from tqdm import tqdm
from PIL import Image
from PIL import ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True
from concurrent.futures import ThreadPoolExecutor, wait, ALL_COMPLETED

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36'
}


def download_image(url_path_tuple):
    url_image, path_save = url_path_tuple
    r = requests.get(url_image, headers=headers)
    with open(path_save, "wb") as f:
        f.write(r.content)
    im = Image.open(path_save)
    im.save(path_save, quality=20)


def download_image_list(meta_json, dir_save):
    if not os.path.exists(meta_json):
        print('[ERROR] input_metadata_json does not exist.')
    metadata = json.load(open(meta_json))
    url_list = []
    save_paths = []
    for doc_id in tqdm(metadata):
        for img_id in metadata[doc_id]:
            url_image = metadata[doc_id][img_id]['url']
            suffix_image = metadata[doc_id][img_id]['url'].split('.')[-1]
            image_path_save = os.path.join(dir_save, '%s_%s.%s' % (doc_id, img_id, suffix_image))
            url_list.append(url_image)
            save_paths.append(image_path_save)
    return url_list, save_paths

if __name__ == '__main__':
    input_metadata_json = "./voa_img_dataset.json"
    output_image_dir = "./voa_image"
    url_list, save_paths = download_image_list(input_metadata_json, output_image_dir)

    executor = ThreadPoolExecutor(max_workers=30)
    future_tasks = [executor.submit(download_image, url_path_tuple) for url_path_tuple in zip(url_list, save_paths)]
    wait(future_tasks, return_when=ALL_COMPLETED)

    print("All images download complete.")
```
Note that you should have sufficiently large disk space to restore the images. It may be a necessity that you have a very good VPN. If you are not confident about your VPN, it is a good choice to split voa_img_dataset.json into several small fractions and download each of them one by one. Hope that my suggestion can help you more or less!

**Comment by ghost** [comment]
Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian.

**Comment by zyz0000** [comment]
The compressed images are 35GB in total. If one does not compress them, the images may take more than 2TB.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyz0000/ACE2005_preprocessing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 晚上10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zyz0000/ACE2005_preprocessing] VOA (Issue #1)





 
Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian. BTW, do you know roughly the number of images? I've downloaded nearly 120 thousands of imgaes, but it still does not terminate. I worried about the limited spce of the disk.

**Comment by ghost** [comment]
Many thanks. BTW, have you ever execute the code of the CLIP-Event, which is a followup work of M2E2. :)

**Comment by zyz0000** [comment]
No. I have noticed this work, but have not found time to read it. Maybe we can discuss about it in the future.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyz0000/ACE2005_preprocessing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zyz0000/ACE2005_preprocessing] VOA (Issue #1)





 
Many thanks. BTW, have you ever execute the code of the CLIP-Event, which is a followup work of M2E2. :)

**Comment by ghost** [comment]
Hahah, yep. Thank you very much.

**Comment by Kuangdd01** [comment]
> The compressed images are 35GB in total. If one does not compress them, the images may take more than 2TB.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zyz0000/ACE2005_preprocessing" ***@***.***&gt;; 发送时间:&nbsp;2022年10月10日(星期一) 晚上10:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zyz0000/ACE2005_preprocessing] VOA (Issue #1) Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian. BTW, do you know roughly the number of images? I've downloaded nearly 120 thousands of imgaes, but it still does not terminate. I worried about the limited spce of the disk. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

It looks like this dataset download is a big project and I'm starting to wonder if I can reproduce this work for M2E2, I'd like to ask if you've managed to reproduce the results? I am still struggling with this. :(

**Comment by Kuangdd01** [comment]
> Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian.

Hello, have u reproduced m2e2 this task already? I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images`
![groundingError](https://user-images.githubusercontent.com/82590017/204093133-58bf89da-42c5-49e2-86d4-522a01ccc6c8.png)
 infomation. It seemed that joint trainning ignored the voa dataset.... without any error thrown..:(

**Comment by ghost** [comment]
> I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images`

Yes, I have ran the code of training a object_based joint training model already. I've never encounter this mistake.

**Comment by ghost** [comment]
> > The compressed images are 35GB in total. If one does not compress them, the images may take more than 2TB.
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "zyz0000/ACE2005_preprocessing" _**@**_._**>; 发送时间: 2022年10月10日(星期一) 晚上10:30 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [zyz0000/ACE2005_preprocessing] VOA (Issue #1) Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian. BTW, do you know roughly the number of images? I've downloaded nearly 120 thousands of imgaes, but it still does not terminate. I worried about the limited spce of the disk. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> It looks like this dataset download is a big project and I'm starting to wonder if I can reproduce this work for M2E2, I'd like to ask if you've managed to reproduce the results? I am still struggling with this. :(

Hi, I've reproduced the code, may I help you? BTW, the dataset mentioned in the original paper contains 245 documents, but I only found 235 articles when I downloaded it. Do you meet the same situation?

**Comment by zyz0000** [comment]
> > Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian.
> 
> Hello, have u reproduced m2e2 this task already? I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images` ![groundingError](https://user-images.githubusercontent.com/82590017/204093133-58bf89da-42c5-49e2-86d4-522a01ccc6c8.png) infomation. It seemed that joint trainning ignored the voa dataset.... without any error thrown..:(

I checked the training log. Just like what @YorickZilin said, if you run train_joint_obj.sh, the log looks like this:
![捕获9](https://user-images.githubusercontent.com/42911581/204139027-d71334f5-f687-4675-942b-7c3ed98cf2be.JPG)
But if you run train_joint_att.sh, the log is the same with yours.

**Comment by zyz0000** [comment]
> > > The compressed images are 35GB in total. If one does not compress them, the images may take more than 2TB.
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "zyz0000/ACE2005_preprocessing" _**@**_._**>; 发送时间: 2022年10月10日(星期一) 晚上10:30 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [zyz0000/ACE2005_preprocessing] VOA (Issue #1) Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian. BTW, do you know roughly the number of images? I've downloaded nearly 120 thousands of imgaes, but it still does not terminate. I worried about the limited spce of the disk. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > It looks like this dataset download is a big project and I'm starting to wonder if I can reproduce this work for M2E2, I'd like to ask if you've managed to reproduce the results? I am still struggling with this. :(
> 
> Hi, I've reproduced the code, may I help you? BTW, the dataset mentioned in the original paper contains 245 documents, but I only found 235 articles when I downloaded it. Do you meet the same situation?

I also get 235 articles.

**Comment by ghost** [comment]
> > > > The compressed images are 35GB in total. If one does not compress them, the images may take more than 2TB.
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: "zyz0000/ACE2005_preprocessing" _**@**_._**>; 发送时间: 2022年10月10日(星期一) 晚上10:30 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [zyz0000/ACE2005_preprocessing] VOA (Issue #1) Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian. BTW, do you know roughly the number of images? I've downloaded nearly 120 thousands of imgaes, but it still does not terminate. I worried about the limited spce of the disk. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > > 
> > > 
> > > It looks like this dataset download is a big project and I'm starting to wonder if I can reproduce this work for M2E2, I'd like to ask if you've managed to reproduce the results? I am still struggling with this. :(
> > 
> > 
> > Hi, I've reproduced the code, may I help you? BTW, the dataset mentioned in the original paper contains 245 documents, but I only found 235 articles when I downloaded it. Do you meet the same situation?
> 
> I also get 235 articles.

Hi Yuzhe, many thanks for your reply. Sorry to bother you again. I found there is a sentence id in the m2e2_annotations/image_multimedia_event.json (e.g., "sentence_id": "VOA_EN_NW_2015.11.26.3074855_5"), but the articles in the file of 'm2e2_rawdata/article/...txt' doesn't have this label. I think it is necessary to get the right sentence id because the labels in crossmedia_coref.txt are represented by sentence id. Could you please let me know how to get the sentence_id. I notice you use 'nltk.sent_tokenize' when processing the ACE, but it seems not suitable to M2E2. For example (the first data point in text_multimedia_event.json), if I use 'nltk.sent_tokenize' to parse the  VOA_EN_NW_2015.11.26.3074855.rsd.txt, this is the 4th sentence instead of 5.

"sentence_id": "VOA_EN_NW_2015.11.26.3074855_5",
        "sentence_start": 792,
        "sentence_end": 1031,
        "sentence": "Two Chicago police officers take a man into custody during a protest march, Wednesday, Nov. 25, 2015, in Chicago, the day after murder charges were brought against police officer Jason Van Dyke in the killing of 17-year-old Laquan McDonald",

**Comment by Kuangdd01** [comment]
>

> > > Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian.
> > 
> > 
> > Hello, have u reproduced m2e2 this task already? I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images` ![groundingError](https://user-images.githubusercontent.com/82590017/204093133-58bf89da-42c5-49e2-86d4-522a01ccc6c8.png) infomation. It seemed that joint trainning ignored the voa dataset.... without any error thrown..:(
> 
> I checked the training log. Just like what @YorickZilin said, if you run train_joint_obj.sh, the log looks like this: ![捕获9](https://user-images.githubusercontent.com/42911581/204139027-d71334f5-f687-4675-942b-7c3ed98cf2be.JPG) But if you run train_joint_att.sh, the log is the same with yours.

Yes, I tried the script `train_joint_att.sh`, and it seems something wrong with this code. what is more,  I want to know that the whole `voa-dataset` occupies 2TB in disk. Is it true? I just download a small part of it..  TOT

**Comment by Kingslry-git** [comment]
>
Many thanks to your kind reply! I will try the other script!  thxx!

**Comment by Kuangdd01** [comment]
> > I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images`
> 
> Yes, I have ran the code of training a object_based joint training model already. I've never encounter this mistake.

Many thanks to your kind reply! I will try the other script! thxx!

**Comment by YorickZilin** [comment]
> > > I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images`
> > 
> > 
> > Yes, I have ran the code of training a object_based joint training model already. I've never encounter this mistake.
> 
> Many thanks to your kind reply! I will try the other script! thxx!

**Comment by ghost** [comment]
> > 
> 
> > > > Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian.
> > > 
> > > 
> > > Hello, have u reproduced m2e2 this task already? I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images` ![groundingError](https://user-images.githubusercontent.com/82590017/204093133-58bf89da-42c5-49e2-86d4-522a01ccc6c8.png) infomation. It seemed that joint trainning ignored the voa dataset.... without any error thrown..:(
> > 
> > 
> > I checked the training log. Just like what @YorickZilin said, if you run train_joint_obj.sh, the log looks like this: ![捕获9](https://user-images.githubusercontent.com/42911581/204139027-d71334f5-f687-4675-942b-7c3ed98cf2be.JPG) But if you run train_joint_att.sh, the log is the same with yours.
> 
> Yes, I tried the script `train_joint_att.sh`, and it seems something wrong with this code. what is more, I want to know that the whole `voa-dataset` occupies 2TB in disk. Is it true? I just download a small part of it.. TOT

Actually, it cost me 35GB. BTW, can you parse the sentence with a right sentence id? I found there is a sentence id in the m2e2_annotations/image_multimedia_event.json (e.g., "sentence_id": "VOA_EN_NW_2015.11.26.3074855_5"), but the articles in the file of 'm2e2_rawdata/article/...txt' doesn't have this label. I think it is necessary to get the right sentence id because the labels in crossmedia_coref.txt are represented by sentence id. Could you please let me know how to get the sentence_id. I notice you use 'nltk.sent_tokenize' when processing the ACE, but it seems not suitable to M2E2. For example (the first data point in text_multimedia_event.json), if I use 'nltk.sent_tokenize' to parse the VOA_EN_NW_2015.11.26.3074855.rsd.txt, this is the 4th sentence instead of 5.

"sentence_id": "VOA_EN_NW_2015.11.26.3074855_5",
"sentence_start": 792,
"sentence_end": 1031,
"sentence": "Two Chicago police officers take a man into custody during a protest march, Wednesday, Nov. 25, 2015, in Chicago, the day after murder charges were brought against police officer Jason Van Dyke in the killing of 17-year-old Laquan McDonald",

**Comment by zyz0000** [comment]
> > > 
> > 
> > 
> > > > > Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian.
> > > > 
> > > > 
> > > > Hello, have u reproduced m2e2 this task already? I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images` ![groundingError](https://user-images.githubusercontent.com/82590017/204093133-58bf89da-42c5-49e2-86d4-522a01ccc6c8.png) infomation. It seemed that joint trainning ignored the voa dataset.... without any error thrown..:(
> > > 
> > > 
> > > I checked the training log. Just like what @YorickZilin said, if you run train_joint_obj.sh, the log looks like this: ![捕获9](https://user-images.githubusercontent.com/42911581/204139027-d71334f5-f687-4675-942b-7c3ed98cf2be.JPG) But if you run train_joint_att.sh, the log is the same with yours.
> > 
> > 
> > Yes, I tried the script `train_joint_att.sh`, and it seems something wrong with this code. what is more, I want to know that the whole `voa-dataset` occupies 2TB in disk. Is it true? I just download a small part of it.. TOT
> 
> Actually, it cost me 35GB. BTW, can you parse the sentence with a right sentence id? I found there is a sentence id in the m2e2_annotations/image_multimedia_event.json (e.g., "sentence_id": "VOA_EN_NW_2015.11.26.3074855_5"), but the articles in the file of 'm2e2_rawdata/article/...txt' doesn't have this label. I think it is necessary to get the right sentence id because the labels in crossmedia_coref.txt are represented by sentence id. Could you please let me know how to get the sentence_id. I notice you use 'nltk.sent_tokenize' when processing the ACE, but it seems not suitable to M2E2. For example (the first data point in text_multimedia_event.json), if I use 'nltk.sent_tokenize' to parse the VOA_EN_NW_2015.11.26.3074855.rsd.txt, this is the 4th sentence instead of 5.
> 
> "sentence_id": "VOA_EN_NW_2015.11.26.3074855_5", "sentence_start": 792, "sentence_end": 1031, "sentence": "Two Chicago police officers take a man into custody during a protest march, Wednesday, Nov. 25, 2015, in Chicago, the day after murder charges were brought against police officer Jason Van Dyke in the killing of 17-year-old Laquan McDonald",

I checked your problem. I think that it is purely annotation error. By the way, does this annotation error happen frequently in M2E2 dataset?

**Comment by ghost** [comment]
> > > > 
> > > 
> > > 
> > > > > > Thanks for your kindness. I tried the script you offered, it does work. Many thanks agian.
> > > > > 
> > > > > 
> > > > > Hello, have u reproduced m2e2 this task already? I encountered some issues when I began to train joint model, I can't get my grounding `captions`and `images` ![groundingError](https://user-images.githubusercontent.com/82590017/204093133-58bf89da-42c5-49e2-86d4-522a01ccc6c8.png) infomation. It seemed that joint trainning ignored the voa dataset.... without any error thrown..:(
> > > > 
> > > > 
> > > > I checked the training log. Just like what @YorickZilin said, if you run train_joint_obj.sh, the log looks like this: ![捕获9](https://user-images.githubusercontent.com/42911581/204139027-d71334f5-f687-4675-942b-7c3ed98cf2be.JPG) But if you run train_joint_att.sh, the log is the same with yours.
> > > 
> > > 
> > > Yes, I tried the script `train_joint_att.sh`, and it seems something wrong with this code. what is more, I want to know that the whole `voa-dataset` occupies 2TB in disk. Is it true? I just download a small part of it.. TOT
> > 
> > 
> > Actually, it cost me 35GB. BTW, can you parse the sentence with a right sentence id? I found there is a sentence id in the m2e2_annotations/image_multimedia_event.json (e.g., "sentence_id": "VOA_EN_NW_2015.11.26.3074855_5"), but the articles in the file of 'm2e2_rawdata/article/...txt' doesn't have this label. I think it is necessary to get the right sentence id because the labels in crossmedia_coref.txt are represented by sentence id. Could you please let me know how to get the sentence_id. I notice you use 'nltk.sent_tokenize' when processing the ACE, but it seems not suitable to M2E2. For example (the first data point in text_multimedia_event.json), if I use 'nltk.sent_tokenize' to parse the VOA_EN_NW_2015.11.26.3074855.rsd.txt, this is the 4th sentence instead of 5.
> > "sentence_id": "VOA_EN_NW_2015.11.26.3074855_5", "sentence_start": 792, "sentence_end": 1031, "sentence": "Two Chicago police officers take a man into custody during a protest march, Wednesday, Nov. 25, 2015, in Chicago, the day after murder charges were brought against police officer Jason Van Dyke in the killing of 17-year-old Laquan McDonald",
> 
> I checked your problem. I think that it is purely annotation error. By the way, does this annotation error happen frequently in M2E2 dataset?

Yes, there are some problems. But the problem I mentioned seems to have no effect on the results because the input doesn't contain the raw_data/articles.

**Comment by ghost** [comment]
Hi Yuzhe. Have you ever run the 'eval' scripts on the dataset of M2E2. It seems there is no code about the evaluation of multimedia events. The input files in the scripts are listed below, but the author doesn't give them.
--gt_voa_image $datadir"/voa_anno_m2e2/image_event.json" \
--gt_voa_text $datadir"/voa_anno_m2e2/article_event.json" \
--gt_voa_align $datadir"/voa_anno_m2e2/article_event.json" \

**Comment by zyz0000** [comment]
> Hi Yuzhe. Have you ever run the 'eval' scripts on the dataset of M2E2. It seems there is no code about the evaluation of multimedia events. The input files in the scripts are listed below, but the author doesn't give them. --gt_voa_image $datadir"/voa_anno_m2e2/image_event.json" --gt_voa_text $datadir"/voa_anno_m2e2/article_event.json" --gt_voa_align $datadir"/voa_anno_m2e2/article_event.json" \

Here is the link containing image_event.json and article_event.json: https://drive.google.com/drive/folders/18n4_kuiW4nxZofT8VcwhsDD12htqqADc?usp=sharing

**Comment by YorickZilin** [comment]
> 
Got it!
Thank you so much!

**Comment by ghost** [comment]
> > Hi Yuzhe. Have you ever run the 'eval' scripts on the dataset of M2E2. It seems there is no code about the evaluation of multimedia events. The input files in the scripts are listed below, but the author doesn't give them. --gt_voa_image $datadir"/voa_anno_m2e2/image_event.json" --gt_voa_text $datadir"/voa_anno_m2e2/article_event.json" --gt_voa_align $datadir"/voa_anno_m2e2/article_event.json" \
> 
> Here is the link containing image_event.json and article_event.json: https://drive.google.com/drive/folders/18n4_kuiW4nxZofT8VcwhsDD12htqqADc?usp=sharing

Got it! Thank you so much!!!

**Comment by baoqianyue** [comment]
> Hi Yuzhe. Have you ever run the 'eval' scripts on the dataset of M2E2. It seems there is no code about the evaluation of multimedia events. The input files in the scripts are listed below, but the author doesn't give them. --gt_voa_image $datadir"/voa_anno_m2e2/image_event.json" --gt_voa_text $datadir"/voa_anno_m2e2/article_event.json" --gt_voa_align $datadir"/voa_anno_m2e2/article_event.json" \

Hello, I am also starting to reproduce m2e2 now, and I really hope to join you @zyz0000  @YorickZilin . I tried to download these evaluation jsons from the Google drive link you gave, but it seems that there are permission restrictions. Can you share it with me again?

**Comment by haiyLiu** [comment]
@baoqianyue Hi, I have the same problem, Do you obtain image_event.json and article_event.json files?

**Comment by haiyLiu** [comment]
@YorickZilin Hi, could you share image_event.json and article_event.json .etc files?

**Comment by HXYM** [comment]
Hi, I compared your preprocessed data structure and the original author of the data structure,they are not very similar to the sample, have you run the text event extraction model code?

**Comment by baoqianyue** [comment]
> @baoqianyue Hi, I have the same problem, Do you obtain image_event.json and article_event.json files?

This problem still exists, and I have not obtained these two files. If you can obtain them through other channels, please share with me, thank you.

**Comment by baoqianyue** [comment]
> @baoqianyue Hi, I have the same problem, Do you obtain image_event.json and article_event.json files?

@haiyLiu This problem still exists, and I have not obtained these two files. If you can obtain them through other channels, please share with me, thank you.

**Comment by HXYM** [comment]
> > > Hi Yuzhe. Have you ever run the 'eval' scripts on the dataset of M2E2. It seems there is no code about the evaluation of multimedia events. The input files in the scripts are listed below, but the author doesn't give them. --gt_voa_image $datadir"/voa_anno_m2e2/image_event.json" --gt_voa_text $datadir"/voa_anno_m2e2/article_event.json" --gt_voa_align $datadir"/voa_anno_m2e2/article_event.json" \
> > 
> > 
> > Here is the link containing image_event.json and article_event.json: https://drive.google.com/drive/folders/18n4_kuiW4nxZofT8VcwhsDD12htqqADc?usp=sharing
> 
> Got it! Thank you so much!!!

Sorry to bother you,did you get the three files, I would be grateful if you could share them with me, because the author closed the google cloud Permissions, so the previous link can no longer get the file.

**Comment by Eliauk-TiAmo** [comment]
@baoqianyue @YorickZilin Hi, I have recently been trying to reproduce this task as well, and in the process of downloading the relevant files, I found that I was not able to find the file $glovedir"/glove.840B.300d.txt", do you have any ideas please, thank you for sharing and I hope to get your reply.

**Comment by BudBudding** [comment]
> > > Hi Yuzhe. Have you ever run the 'eval' scripts on the dataset of M2E2. It seems there is no code about the evaluation of multimedia events. The input files in the scripts are listed below, but the author doesn't give them. --gt_voa_image $datadir"/voa_anno_m2e2/image_event.json" --gt_voa_text $datadir"/voa_anno_m2e2/article_event.json" --gt_voa_align $datadir"/voa_anno_m2e2/article_event.json" \
> > 
> > 
> > Here is the link containing image_event.json and article_event.json: https://drive.google.com/drive/folders/18n4_kuiW4nxZofT8VcwhsDD12htqqADc?usp=sharing
> 
> Got it! Thank you so much!!!

Hello, I'm very sorry to bother you. A few days ago, I noticed that you have closed this issue on your end. May I ask if it is convenient for you to provide these. json files over there.
